import type { DistrictProfile, DistrictCode, Province, CropType } from "./types"

export const DISTRICTS: Partial<Record<DistrictCode, DistrictProfile>> = {
  // Kigali Province
  Nyarugenge: {
    id: "Nyarugenge",
    name: "Nyarugenge",
    province: "Kigali",
    coordinates: [-1.9441, 30.0619],
    population: 290564,
    farmingHouseholds: 12500,
    soilTypes: ["Clay", "Loam"],
    climateZone: "Tropical Highland",
    recommendedCrops: ["beans", "sweet_potato", "banana"],
    marketDays: ["Monday", "Thursday", "Saturday"],
    averageIncome: 180000,
    povertyRate: 0.12,
    cropProductivity: {
      beans: 1.2,
      sweet_potato: 8.5,
      banana: 15.2,
      maize: 2.1,
      cassava: 12.0,
      irish_potato: 18.5,
      coffee: 0.8,
      tea: 0,
      rice: 0,
      wheat: 0,
      sorghum: 1.5,
      groundnuts: 0.9,
    },
    priceVolatility: {
      beans: 0.15,
      sweet_potato: 0.25,
      banana: 0.18,
      maize: 0.22,
      cassava: 0.2,
      irish_potato: 0.3,
      coffee: 0.35,
      tea: 0,
      rice: 0,
      wheat: 0,
      sorghum: 0.28,
      groundnuts: 0.32,
    },
  },
  Gasabo: {
    id: "Gasabo",
    name: "Gasabo",
    province: "Kigali",
    coordinates: [-1.9706, 30.1044],
    population: 530515,
    farmingHouseholds: 28500,
    soilTypes: ["Clay", "Sandy Loam"],
    climateZone: "Tropical Highland",
    recommendedCrops: ["maize", "beans", "irish_potato", "banana"],
    marketDays: ["Tuesday", "Friday", "Sunday"],
    averageIncome: 195000,
    povertyRate: 0.1,
    cropProductivity: {
      maize: 2.8,
      beans: 1.4,
      irish_potato: 22.0,
      banana: 18.5,
      sweet_potato: 9.2,
      cassava: 14.5,
      coffee: 1.2,
      tea: 0,
      rice: 0,
      wheat: 0,
      sorghum: 2.1,
      groundnuts: 1.1,
    },
    priceVolatility: {
      maize: 0.2,
      beans: 0.18,
      irish_potato: 0.35,
      banana: 0.16,
      sweet_potato: 0.22,
      cassava: 0.18,
      coffee: 0.4,
      tea: 0,
      rice: 0,
      wheat: 0,
      sorghum: 0.25,
      groundnuts: 0.3,
    },
  },
  Kicukiro: {
    id: "Kicukiro",
    name: "Kicukiro",
    province: "Kigali",
    coordinates: [-1.9685, 30.1029],
    population: 318357,
    farmingHouseholds: 18200,
    soilTypes: ["Clay", "Loam"],
    climateZone: "Tropical Highland",
    recommendedCrops: ["beans", "maize", "sweet_potato"],
    marketDays: ["Wednesday", "Saturday"],
    averageIncome: 175000,
    povertyRate: 0.14,
    cropProductivity: {
      beans: 1.3,
      maize: 2.5,
      sweet_potato: 8.8,
      banana: 16.0,
      cassava: 13.2,
      irish_potato: 19.5,
      coffee: 0.9,
      tea: 0,
      rice: 0,
      wheat: 0,
      sorghum: 1.8,
      groundnuts: 1.0,
    },
    priceVolatility: {
      beans: 0.17,
      maize: 0.23,
      sweet_potato: 0.26,
      banana: 0.19,
      cassava: 0.21,
      irish_potato: 0.32,
      coffee: 0.38,
      tea: 0,
      rice: 0,
      wheat: 0,
      sorghum: 0.27,
      groundnuts: 0.31,
    },
  },
  // Add more districts - for demo purposes, I'll add a few key ones
  Musanze: {
    id: "Musanze",
    name: "Musanze",
    province: "Northern",
    coordinates: [-1.4983, 29.6356],
    population: 368267,
    farmingHouseholds: 65800,
    soilTypes: ["Volcanic", "Clay"],
    climateZone: "Tropical Highland",
    recommendedCrops: ["irish_potato", "maize", "beans", "tea"],
    marketDays: ["Monday", "Wednesday", "Friday"],
    averageIncome: 145000,
    povertyRate: 0.22,
    cropProductivity: {
      irish_potato: 28.5,
      maize: 3.2,
      beans: 1.6,
      tea: 2.8,
      banana: 20.5,
      sweet_potato: 10.5,
      cassava: 15.8,
      coffee: 1.5,
      rice: 0,
      wheat: 1.2,
      sorghum: 2.5,
      groundnuts: 1.3,
    },
    priceVolatility: {
      irish_potato: 0.28,
      maize: 0.18,
      beans: 0.16,
      tea: 0.45,
      banana: 0.15,
      sweet_potato: 0.2,
      cassava: 0.17,
      coffee: 0.42,
      rice: 0,
      wheat: 0.35,
      sorghum: 0.22,
      groundnuts: 0.28,
    },
  },
  Huye: {
    id: "Huye",
    name: "Huye",
    province: "Southern",
    coordinates: [-2.5967, 29.7394],
    population: 381900,
    farmingHouseholds: 72500,
    soilTypes: ["Clay", "Sandy Clay"],
    climateZone: "Tropical Highland",
    recommendedCrops: ["coffee", "banana", "beans", "maize"],
    marketDays: ["Tuesday", "Thursday", "Saturday"],
    averageIncome: 135000,
    povertyRate: 0.28,
    cropProductivity: {
      coffee: 2.2,
      banana: 22.8,
      beans: 1.5,
      maize: 2.9,
      irish_potato: 20.5,
      sweet_potato: 11.2,
      cassava: 16.5,
      tea: 1.8,
      rice: 0,
      wheat: 0.8,
      sorghum: 2.8,
      groundnuts: 1.4,
    },
    priceVolatility: {
      coffee: 0.48,
      banana: 0.14,
      beans: 0.19,
      maize: 0.21,
      irish_potato: 0.3,
      sweet_potato: 0.23,
      cassava: 0.19,
      tea: 0.52,
      rice: 0,
      wheat: 0.4,
      sorghum: 0.26,
      groundnuts: 0.33,
    },
  },
  // Note: In production, all 30 districts would be included
} as const

// Complete district lists by province
const PROVINCE_DISTRICTS: Record<Province, DistrictCode[]> = {
  Kigali: ["Gasabo", "Kicukiro", "Nyarugenge"],
  Eastern: ["Bugesera", "Gatsibo", "Kayonza", "Kirehe", "Ngoma", "Nyagatare", "Rwamagana"],
  Northern: ["Burera", "Gakenke", "Gicumbi", "Musanze", "Rulindo"],
  Southern: ["Gisagara", "Huye", "Kamonyi", "Muhanga", "Nyamagabe", "Nyanza", "Nyaruguru", "Ruhango"],
  Western: ["Karongi", "Ngororero", "Nyabihu", "Nyamasheke", "Rubavu", "Rusizi", "Rutsiro"],
}

const defaultProductivity: Record<CropType, number> = {
  maize: 0,
  beans: 0,
  sorghum: 0,
  sweet_potato: 0,
  cassava: 0,
  irish_potato: 0,
  banana: 0,
  coffee: 0,
  tea: 0,
  rice: 0,
  wheat: 0,
  groundnuts: 0,
}

const defaultVolatility: Record<CropType, number> = {
  maize: 0.2,
  beans: 0.2,
  sorghum: 0.2,
  sweet_potato: 0.2,
  cassava: 0.2,
  irish_potato: 0.2,
  banana: 0.2,
  coffee: 0.2,
  tea: 0.2,
  rice: 0.2,
  wheat: 0.2,
  groundnuts: 0.2,
}

const defaultCropsByProvince: Record<Province, CropType[]> = {
  Kigali: ["beans", "maize", "banana"],
  Eastern: ["maize", "beans", "sorghum", "cassava"],
  Northern: ["irish_potato", "beans", "maize", "tea"],
  Southern: ["coffee", "banana", "beans", "maize"],
  Western: ["banana", "irish_potato", "tea", "coffee"],
}

const createDefaultDistrict = (id: DistrictCode, province: Province): DistrictProfile => ({
  id,
  name: id,
  province,
  coordinates: [0, 0],
  population: 0,
  farmingHouseholds: 0,
  soilTypes: [],
  climateZone: "",
  recommendedCrops: defaultCropsByProvince[province],
  marketDays: [],
  averageIncome: 0,
  povertyRate: 0,
  cropProductivity: { ...defaultProductivity },
  priceVolatility: { ...defaultVolatility },
})

export const getDistrictsByProvince = (province: Province): DistrictProfile[] => {
  const list = PROVINCE_DISTRICTS[province] || []
  return list.map((code) => DISTRICTS[code] ?? createDefaultDistrict(code, province))
}

export const getRecommendedCropsForDistrict = (districtCode: DistrictCode): CropType[] => {
  return DISTRICTS[districtCode]?.recommendedCrops || []
}

export const getDistrictProfile = (districtCode: DistrictCode): DistrictProfile | null => {
  const fromMap = DISTRICTS[districtCode]
  if (fromMap) return fromMap
  // Try to infer province membership
  const province = (Object.entries(PROVINCE_DISTRICTS).find(([, codes]) => codes.includes(districtCode))?.[0] ||
    null) as Province | null
  return province ? createDefaultDistrict(districtCode, province) : null
}
